// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znzpuyhfdpyjmjtwfqzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuenB1eWhmZHB5am1qdHdmcXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mzc4NTksImV4cCI6MjA2NjUxMzg1OX0.V-WSPhK2NpXtD0NiDUA1gRF6xKw1sxiD8YIPcYDLKFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);